# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: pro-deploy

on:
  push:
    branches: ["production"]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'

    - name: Install
      run: pnpm install

    - name: Build
      run: pnpm build
    - name: Deploy
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_FED }}
        REMOTE_HOST: 172.17.129.146
        REMOTE_USER: blossom
        SOURCE: dist/uportal-web/browser/
        TARGET: /data/blossom/${{ github.repository }}/${{ github.sha }}/
        SCRIPT_BEFORE: |
          mkdir -p ~/${{ github.repository_owner }}
          mkdir -p /data/blossom/${{ github.repository }};
        SCRIPT_AFTER: |
          rm -rf ~/${{ github.repository }}; ln -s /data/blossom/${{ github.repository }}/${{ github.sha }} ~/${{ github.repository }};
          cd /data/blossom/${{ github.repository }}; dirs_to_delete=$(ls -dtr -- */ | head -n -3); for dir in $dirs_to_delete; do rm -rf "$dir"; done;
